apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-logstash
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:5.4.0