apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk-stack
  labels:
    role: elk-stack
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP

   

