apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-ek
  labels:
    app: ek-stack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ek-stack
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      # Kibana container
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.4.0
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://127.0.0.1:9200"
        #  - name: "KIBANA_BASE_URL"
        #    value: "/api/v1/proxy/namespaces/kube-system/services/kibana-logging"
        ports: 
        - containerPort: 5601
      # Elasticsearch container  
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        ports:
        - containerPort: 9200
        


      
