apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
      # Init Containers in V 1.5 API  
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      # Elasticsearch container  
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        ports:
        - containerPort: 9200

      
