apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-elkstack
  labels:
    app: elkstack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elkstack
      # Init Containers in V 1.5 API  
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      # Logstash container
      - name: logstash
        image: docker.elastic.co/logstash/logstash:5.4.0
        volumeMounts: 
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/
        ports: 
        - containerPort: 8080
      # Elasticsearch container  
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        ports:
        - containerPort: 9200
      # Kibana container
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.4.0
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://127.0.0.1:9200"
        #  - name: "KIBANA_BASE_URL"
        #    value: "/api/v1/proxy/namespaces/kube-system/services/kibana-logging"
        ports: 
        - containerPort: 5601
      volumes: 
      - name: config-volume
        configMap:
          name: config-logstash