apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-kibana
  labels:
    app: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      # Kibana container
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.4.0
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://ekstack-service.default.svc.cluster.local:9200"
          #- name: "KIBANA_BASE_URL"
          #  value: "/api/v1/proxy/namespaces/kube-system/services/kibana-logging"
        ports: 
        - containerPort: 5601

        


      
