apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-logstash
  labels:
    app: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      # Logstash container
      - name: logstash
        image: docker.elastic.co/logstash/logstash:5.4.0
        volumeMounts: 
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/
        env:
        - name: XPACK_MONITORING_ENABLED
          value: xpack.monitoring.disabled
        ports: 
        - containerPort: 8080
      # Mounted volume  
      volumes: 
      - name: config-volume
        configMap:
          name: config-logstash

      
