apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastic-stack
  labels:
    app: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:5.4.0
        volumeMounts: 
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/
        ports: 
        - containerPort: 31311
      volumes: 
      - name: config-volume
        configMap:
          name: logstash-config
      
