apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: le-stack
spec:
  replicas: 3
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:5.4.0
        volumeMounts: 
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/
      volumes: 
      - name: config-volume
        configMap:
          name: logstash-config
      
